import { expect, test } from "bun:test";
import { parseSha256Sums } from "./sums";

test("parseSha256Sums reads entries, comments, and blank lines", () => {
    const sums = parseSha256Sums(
        [
            "# generated by release pipeline",
            "",
            `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa  spanical-darwin-arm64`,
            `BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB *spanical-linux-x64`,
        ].join("\n")
    );
    expect(sums["spanical-darwin-arm64"]).toBe("a".repeat(64));
    // Binary-marker asterisk stripped; uppercase hex folded to lowercase.
    expect(sums["spanical-linux-x64"]).toBe("b".repeat(64));
});

test("parseSha256Sums handles CRLF line endings", () => {
    const sums = parseSha256Sums(
        `cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc  spanical-linux-arm64\r\n`
    );
    expect(sums["spanical-linux-arm64"]).toBe("c".repeat(64));
});

test("parseSha256Sums skips malformed lines without failing the rest", () => {
    const sums = parseSha256Sums(
        [
            "not-a-hash-line",
            "short  file",
            `dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd  spanical-darwin-x64`,
        ].join("\n")
    );
    expect(Object.keys(sums)).toEqual(["spanical-darwin-x64"]);
});

test("parseSha256Sums throws on duplicate entries for the same asset", () => {
    const line = `eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee  spanical-darwin-x64`;
    expect(() => parseSha256Sums(`${line}\n${line}`)).toThrow(
        /Duplicate SHA256SUMS entry/
    );
});
